<?php $this->headScript()->captureStart()?>
var c=new clase();
var pararini;
var numb=0;
$(document).ready(
	  function()
	  {
		c.iniciar();		
		c.abrirRect(window.innerHeight/2,window.innerWidth*0.4,window.innerHeight/2,window.innerWidth*0.2,3,$("#centro").width()-1,1,"#centro");
	  }
);
<?php $this->headScript()->captureEnd(); ?>

<div class="datosp">
	<div class="nombre">Diego Pena Gayo</div>
</div>

<div id="centro">
	<div id="contenedor">
		<div class="margenes">
			<div class="dpdcha"><img src="./imagenes/mifoto.jpg"></img></div>
		</div>
		<div class="margenes">
			<div class="encabezados">Experiencia laboral</div>
			<div class="puesto"><span style="font-weight:bold">Operador de sistemas en Uniway</span>, Madrid, desde el 08/2003 hasta el 12/2004.</div>
			<div class="puesto"><span style="font-weight:bold">Administrador de windows en BBVA</span>, Madrid, desde el 04/2005 hasta el 11/2005.</div>
			<div class="puesto"><span style="font-weight:bold">Programador PHP en vía intermedia</span>, Madrid, desde el 02/2007 hasta el 02/2008.</div>
			<div>Programación con PHP5, MySQL5, HTML5, CSS3, DOM, Ajax, Xajax, WAMP.</div>
			<div class="puesto"><span style="font-weight:bold">Programador PHP en Cifesal</span>, Madrid, desde el 05/2008 hasta el 07/2011</div>
			<div>Administración, programación y resolución de incidencias para la web interna de la empresa y su base de datos. Programación con PHP5 orientado a objetos con MVC, Javascript orientado a objetos, Administración y programación MySQL5, HTML5, CSS3, DOM, Xajax, WAMP, Eclipse, Subversion, Git, Tcpdf, Pear DB y Mail, Dreamweaver, Fireworks.</div>
		</div>
		
		<div class="margenes">
			<div class="encabezados">Formación</div>
			<div class="puesto"><span style="font-weight:bold">Título MCSE, ingeniero de sistemas de Microsoft para Windows 2000.</span></div>
			<div class="puesto"><span style="font-weight:bold">Título CCNA.</span></div>
			<div class="puesto"><span style="font-weight:bold">Título Unix Solaris 8, parte I.</span></div>
			<div class="puesto"><span style="font-weight:bold">Master en Cisco, Unix, y Windows 2000 en Microforum, Madrid (636h. De 11/2002-06/2003).</span></div>
			<div class="puesto"><span style="font-weight:bold">Diplomado en Empresas y Actividades turísticas de 1992-1996.</span></div>
		</div>
		
		<div class="margenes">
			<div class="encabezados">Otros conocimientos</div>
			<div class="puesto">Avanzados en Zend, Jquery, Json, Canvas, Unity3D con C# y UnityScript, Ubuntu nivel usuario, WebGL nivel medio.</div>
		</div>
		
		<div class="margenes">
			<div class="encabezados">Idiomas</div>
			<div class="puesto"><span style="font-weight:bold">Inglés</span> nivel muy alto escrito y leído y medio hablado. Nivel B2 con el Título English First Certificate.</span></div>
		</div>	
	</div>
</div>

<div class="enlaces">
	<div class="contacto"><a class='nodeco'>diegopenagayo@hotmail.com</a></div>
	<div class="curriculum"><a href="#" id="curriculum">Currículum</a></div>
	<div class="perfil"><a href="#" class='nodeco' id="perfil">Perfil</a></div>
	<!--<div class="info"><a href="#" class='nodeco'>Información sobre la web</a></div>-->
	
	<div class="pweb">
		<div class="progweb"><a href="#" class="pweb">Programación web</a></div>
		<div id="galeriaimg" class="galeriaimg">
	 		<a href="#" class="galeriaimg">Galería de imagenes</a>
		</div>
	</div>
	<div class="unity3d"><a href="#" id="unity3d">Programación Unity3D</a></div>
	
</div>

<div id="pgpercent">
</div>